version: '3.8'

services:
  service-job:
    build:
      context: .
      dockerfile: ./packages/service-job/Dockerfile
    container_name: service-job
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      SELLERS_API_BASE_URL: https://66ec84422b6cf2b89c5eabf1.mockapi.io/piercloud/api/v1/vendedores
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
